// <auto-generated />
using System;
using HogwartsInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HogwartsAPI.Migrations
{
    [DbContext(typeof(HogwartsContext))]
    [Migration("20210811042059_FixRelationTablesV2")]
    partial class FixRelationTablesV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HogwartsCore.Entities.ApplicationForIncome", b =>
                {
                    b.Property<Guid>("EntityCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasMaxLength(2);

                    b.Property<int>("Identification")
                        .HasColumnType("int")
                        .HasMaxLength(10);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("EntityCode");

                    b.ToTable("Master_ApplicationForIncome");
                });

            modelBuilder.Entity("HogwartsCore.Entities.Fraternity", b =>
                {
                    b.Property<Guid>("EntityCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntityCode");

                    b.ToTable("Master_Fraternity");
                });
#pragma warning restore 612, 618
        }
    }
}
